[app]
api_url = "https://api.orca.wgws.dev"
batch_name = "00"
client_url = "https://orca.wgws.dev"
version = "0.1.0"

[database]
sql_path = "data/orca.db"

[s3]
endpoint = "https://sfo3.digitaloceanspaces.com"
region = "sfo3"
space = "orca"
url = "https://orca.sfo3.cdn.digitaloceanspaces.com"

[logging]
disable_existing_loggers = true
version = 1

[logging.formatters.full]
datefmt = "%Y-%m-%d %H:%M:%S"
format = "%(asctime)s [%(name)s/%(levelname)s] %(message)s"

[logging.formatters.short]
format = "%(levelname)s: %(message)s"

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "short"
level = "INFO"

[logging.handlers.file]
class = "logging.FileHandler"
filename = "log/orca.log"
formatter = "full"
level = "DEBUG"

[logging.loggers.""]
handlers = ["console", "file"]
level = "DEBUG"
propagate = false
